### ISSUE TITLE
Create a project template for a course or teaching lesson

### ISSUE THREAD

**Issue by lwjohnst86** [rostools/prodigenr#8]

**Comment by jcolomb** [comment]
see https://github.com/carpentries-incubator/template for a complete template of carpentry lessons.


Not sure it would make sense to have something equivalent/more basic with prodigenr...

**Comment by lwjohnst86** [comment]
Thanks for that! While I love the Carpentries for what they've done and their impact (and having been an instructor for many years), I personally feel that the Carpentries, while being modern for their time, haven't kept pace with their templates and overall structure. This is a great example of that, where their templates for creating lessons are soooo complicated to me (and I would say I'm pretty knowledgeable/skilled with technical things, so I can't imagine how it might be for others who aren't). Especially when tools like Quarto or Jupyter Book make it soooo easy to create lessons. But yes, I think having a basic template for a Quarto-based (or other tool) lesson structure would be neat!

**Comment by jcolomb** [comment]
they are actually moving to a new template, but I do not know where the template is. They developed it before quarto, but it should still be easier to use, and the syntax looks more like quarto (`:::` instead of shortcodes) ...

(I am also quite thrilled by quarto, still need to try it, but from presentations It looks fantastic)

**Comment by lwjohnst86** [comment]
Quarto really is impressive, sooo smooth of an experience imo! Definitely worth trying!!

**Comment by lwjohnst86** [comment]
I'm minimizing maintenance and scope for this package, so closing this.
